### ISSUE TITLE
Nintendo DNS unblocked

### ISSUE THREAD

**Issue by ShadowninOmega** [darkxex/RipJKAnimeNX#100]
When the program generates the file ``default.txt´´ it deletes the previous settings and makes the switch vulnerable to Nintendo due to a DNS error, I attach the corrected file so you can solve the error as quickly as possible and avoid bans.
[default.txt](https://github.com/darkxex/RipJKAnimeNX/files/9033157/default.txt)
.

**Comment by Kronos2308** [comment]
Solo se reemplaza si 
https://bvc-hac-lp1.cdn.nintendo.net/
se encuentra blokeada.
Siempre q se  recomienda usar Incognito y no confiar en ese dns.

Conclusion:
 me parece perfecto el fichero lo añado ya q funciona, grasias
