### ISSUE TITLE
La aplicación se cierra solo debido a un error

### ISSUE THREAD

**Issue by ShadowninOmega** [darkxex/RipJKAnimeNX#101]
Buenas, basicamente lo que comento en el titulo, al iniciar la applicación mediante el nsp de la ultima versión se cierra sola, no he encontrado el log de errores para adjuntarlo pero adjunto un video donde se ve el error que comento. 
https://user-images.githubusercontent.com/108581881/177977145-f78a13a0-ca34-40af-8a61-e88402c94ff4.mp4

**Comment by ShadowninOmega** [comment]
Tanto el nsp como el nro se siguen cerrando solo en Atmosphere, osea que el programa sigue sin funcionar, asi que no me queda mas remedio que esperar a la proxima update a ver si con suerte se soluciona solo.
Por lo menos tengo el consuelo de que el proyecto aun sigue activo.

**Comment by darkxex** [comment]
La app funciona sin problemas, no has pensado q podría ser tu custom firmware el problema?

**Comment by ShadowninOmega** [comment]
SI, lo he pensado y lo he probado, he cogido una tarjeta nueva y he realizado una instalacion limpia de Atmosphère 1.3.2 y sigue dando el mismo error. Lo probe todo antes de crear el ticket, borrar caches, reinstalar,usar el nro en vez de el nsp y no se porque me sigue dando error. Hasta he redescargado los archivos por si hubiese habido un problema en la descarga que lo pudiese afectar. si se te ocurre algo que no haya probado dimelo para probarlo e intentar llegar a una solucion.
Gracias por tomarte el tiempo de responderme.
