### ISSUE TITLE
La App se queda en Cargando Programación... 

### ISSUE THREAD

**Issue by Thyrnt** [darkxex/RipJKAnimeNX#102]
Hola :D ,no se si te acuerdes de mi pero si por favor  podrías ayudarme otra vez.

Desde la última vez que te escribí no actualize el App pero hoy se comenzó a cerrar así que descargue la última versión, estaba funcionando bien pero quise eliminar el caché y ahí empezó mis problemas.

Acepte eliminar cache se cerro la app y empezó a parpadear el led bastante tiempo, cuando abro la App se queda en cargando y parpadea el led durante 2 minutos.

App: ultima versión 2.5.8
SO: 14.1.2
AMS: 1.3.2
Hekate: 5.8.0
Dns: ninguno
uso lock-logs y incógnito.

No se genera ningún log en la raíz de la SD.

Abro la app (nro) presionando R con otra aplicación porque abriendo el álbum para instalar nsp, lo abro, dice instalando, se cierra y dice "no se a podido iniciar el programa".

**Comment by darkxex** [comment]
debes estar teniendo un drama con tu internet, acabo de instalar https://github.com/darkxex/RipJKAnimeNX/releases/download/2.5.8/RipJKAnimeNX.05B9DB505ABBE000.v0.nsp con Tinfoil y me abre sin problemas, prueba otorgando internet a tu switch con tu teléfono o algo.

**Comment by Thyrnt** [comment]
Hola, en estos momentos no podia probar con otro wifi pero lo queria intentar como sea y en base a lo que me dijiste se me ocurrió cambiar el dns por defecto (de mi operador) por el de google y se solucionó el problema.

Como dijiste el problema era mi internet y seguramente cuando pruebe con los datos mobiles el resultado será bueno.

Me sorprendió que mi operador de Internet lo estuvo bloqueando, voy a avisar esto a otras personas por si no les carga alguna otra página o app.

Una vez más gracias por tus ayuda y conocimientos.

Como sugerencia podrías agregar en que casos se prende el led y que significa porque da curiosidad.
