### ISSUE TITLE
No puedo usar lo como antes 

### ISSUE THREAD

**Issue by Dkdavidlp** [darkxex/RipJKAnimeNX#110]
Ahora siempre cuando entro me redirecta aúna página web y no como antes al Interfaz donde puedo ir a una serie y descargar múltiples episodios ala vez. Uso la versión más reciente y estoy en Versión de Sistema 16.0.0

**Comment by Kronos2308** [comment]
A q te refieres si quieres descargar un cap solo pulsas x encima de este en el menú deslizante 
Si quieres descargar más de uno solo tienes q pulzar B para volver y poner otro capítulo q descargar y así sucesivamente

Aunque ahora q lo dices podría añador la opción de descargar todos de una

**Comment by Dkdavidlp** [comment]
me refiero que antes llegaba al UI i podia descargar las series de alli. ahora me dice "cargando datos..." y se abre una pagina web. Si cierro esa pagina web solo sale el sonido de "are" que me imagino es "error". Solo puedo ir ala Pagina web y nunca llega al UI que tenia antes

**Comment by Dkdavidlp** [comment]
[JK.log](https://github.com/darkxex/RipJKAnimeNX/files/11190183/JK.log)

y porque Github no me deja poner los en directo: https://drive.google.com/drive/folders/1QS-DdV8Z96LKdojoclfh6OBnCfnsVpiW?usp=sharing eso son los .bak

**Comment by Kronos2308** [comment]
# Ultimo LOG
```ini
HEAD> < 1681135014 >
{
    "App": "2.6.7",
    "DeviceID": "XXXXXXXXXXXXX",
    "Firmware": "16.0.0",
    "Model": "ERM",
    "PID": 152,
    "Region": "EUR",
    "Serial": "XAW00000000000",
    "TID": "05B9DB505ABBE000",
    "UNIX": 1681135014,
    "config": {
        "AutoUpdate": 1,
        "Beta": 0,
        "Beta_URL": "",
        "CDNURL": "cdn.jkdesu.com",
        "Logs2File": 0,
        "ReLaunch": 0,
        "author": "darkxex",
        "repo": "RipJKAnimeNX"
    },

}
User Init OK
Gotted user uid:XXXXXXXXXXXXXXXXX
& Chain App >
unable to mount  emmc:/RipJKAnime_NX/themes00.romfs
Json Readed... emmc:/RipJKAnime_NX/AnimeBase.json
Json Readed... emmc:/RipJKAnime_NX/DataBase.json
Json Readed... save:/UserData.json
# Theme: "romfs:/theme/default"
& Chain App >
# DEBUG: OK
# Nintendo Web : 0
# Place DNS
# copy romfs:/default.txt >> sdmc:/atmosphere/hosts/default.txtOK
# Reload DNS
unable to mount  emmc:/RipJKAnime_NX/themes00.romfs
- Error cloudflare active in Web
WEB :https://jkanime.net/
Log to file >
Json: writhen... sdmc:/AnimeBase.json.bak
Json: writhen... sdmc:/DataBase.json.bak
Json: writhen... sdmc:/UserData.json.bak
- Thread Chain Error Catched, Steep#5
# End Thread Chain
& UnChain App >
Cookie Imported... size 3816
Json: writhen... emmc:/RipJKAnime_NX/DataBase.json
Json: writhen... emmc:/RipJKAnime_NX/AnimeBase.json
Json: writhen... save:/UserData.json
ErrorCode: 10
END> < 1681135085 >
```
# 1
estas blokeando los dns de nintendo y la app no puede conectarse bien a la web asi q quita cualquier dns que tengas tiene incognito por dios
# 2
no se pero parece que tienes lleno el almacenamiento interno de la switch no puede ni montar los temas o estan corruptos
# 3 
la app no esta mal funcionando sino q te esta dando unn error de Cloudflare lo cual lya es cosa de la web y tu
# 4
acabo de probar la app en mi consola y funciona bien

## Solucion?
quita cualquier dns que tengas asi como archivo dns en atmosphere/hosts (deja solo default.tx)
libera algo de espacio del almacenamiento del sistema
y por ultimo intenta resetear la app
en modo portatil pulsas + y tocas la papelera

**Comment by Dkdavidlp** [comment]
pues lo voy a intentar gracias. reportare si algo no funciona despues

**Comment by darkxex** [comment]
@Kronos2308 te admiro, yo ya hubiera cerrado el tema.

**Comment by darkxex** [comment]
Te das cuenta de la mierda qué pides, quieres que hagan una versión exclusiva para ti, la app es open source si quieres editar algo hazlo y te compilas algo para ti. Por mi parte daré el tema por cerrado, si Kronos quiere ayudarte lo abrirá de nuevo. Pero este proyecto se inició por amor al arte, pero en el momento en que pase a ser una molestia debe cortarse ahí.

**Comment by darkxex** [comment]
Te das cuenta de la mierda qué pides, quieres que hagan una versión exclusiva para ti, la app es open source si quieres editar algo hazlo y te compilas algo para ti. Por mi parte daré el tema por cerrado, si Kronos quiere ayudarte lo abrirá de nuevo. Pero este proyecto se inició por amor al arte, pero en el momento en que pase a ser una molestia debe cortarse ahí.

**Comment by Kronos2308** [comment]
Si @darkxex  tiene razon el hacer un na versión exclusiva para cada persona q lo pida no es viable
(Lo único que podría hacer es q se pueda cambiar la ruta en el jk.config en futuras versiones) 
También daré el tema por cerrado ya que es un caso especial y no un error perse de la app
@Dkdavidlp como último consejo te diría que borres la carpeta ripjkanime de tu nand con goldleaf o algún otro está en la partición user
