### ISSUE TITLE
Luz Botón home

### ISSUE THREAD

**Issue by Eltapia23** [darkxex/RipJKAnimeNX#95]
Hola, he usado la app y me parece muy buena. Gracias por el proyecto. Sin embargo, al iniciar la app, la luz azul parpadeante del botón home empieza a aparecer. Lo cual puede resultar molesto para ver anime en modo portatil. No encuentro alguna forma de desactivarla, asi que lo posteo aqui a ver que se puede hacer, gracias!

**Comment by darkxex** [comment]
la verdad, el led del botón nunca lo encontré molesto pero fue @Kronos2308  el que integró las funciones de led, preguntale a él si puede hacer algo para que se puedan desactivar o algo.

**Comment by Kronos2308** [comment]
el ld solo parpadea si la app tiene un error 
 o cuando termina una descarga pero mas suave

**Comment by Kronos2308** [comment]
pasanos tu JK.log q esta en la raizz de la sd

**Comment by Eltapia23** [comment]
Se envía por correo? Soy nuevo en Github. Desactive el led mediante un
overlay, pero ahi va de todas formas.

**Comment by Kronos2308** [comment]
eso esq la app te da error

**Comment by Kronos2308** [comment]
psanos el Fichero jk.log por aqui mismo

**Comment by Kronos2308** [comment]
la luz parpadea y dice "Are"?

**Comment by Eltapia23** [comment]
Una voz de monita china? Si. Pero la app funciona bien

**Comment by Kronos2308** [comment]
normalmete solo sale si hay un error de alguna clase
pasame el JK.log y usa esta web https://github.com/darkxex/RipJKAnimeNX/issues/95

**Comment by Kronos2308** [comment]
parasaber de donde viene el error
