### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Oz1442** [darkxex/RipJKAnimeNX#99]
Tras la ultima actualización que lanzaron me a dejado de funcionar para ver anime online como para descargar

**Comment by NecrumBlack** [comment]
Confirmo, ya no conecta con ningún servidor de descarga o streaming

**Comment by darkxex** [comment]
Veré si mañana puedo arreglarla.

**Comment by darkxex** [comment]
https://github.com/darkxex/RipJKAnimeNX/releases/tag/2.5.5 ya chicos descarguen esa actualización y les funcionará @NecrumBlack @Oz1442

**Comment by NecrumBlack** [comment]
Excelente! Muy agradecido 🤘😎
